version: "3"
services:
  node-grunt:
    build:
      context: ./docker-node-grunt
      dockerfile: Dockerfile-build
    volumes:
      - ./client:/app
      - ./server/:/server
    environment:
      - "BUILD_TYPE=${BUILD_TYPE}"
      - "BUILD_WHAT=${BUILD_WHAT}"

volumes:
  mariadb:
