/**
 * Created by Miroku on 11/04/2018.
 */

var Testi = {
    TECHNO_BUBBLING: [
        { delay: 0, text: "Preparing files for software compiling..." },
        { delay: 0, text: "Compiler initialized..." },
        { delay: 100, text: "SGC Block-Chain connections..." },
        { delay: 0, text: "Access data accepted." },
        { delay: 50, text: "Loading development enviornment..." },
        { delay: 0, text: "Development environment loaded." },
        { delay: 100, text: "Analyzing code syntax..." },
        { delay: 100, text: "Searching for security breaches..." },
        { delay: 100, text: "Downloading compression parameters..." },
        { delay: 0, text: "[D423#34C@SGC]: //SGC//Struttura//223//CDN//grv-compression.ez3 >> //Local//Storage//Compression//grv-compression.ez3" },
        { delay: 0, text: "[D423#34C@SGC]: //SGC//Struttura//223//CDN//grv-concat.ez3 >> //Local//Storage//Compression//grv-concat.ez3" },
        { delay: 0, text: "[D423#34C@SGC]: //SGC//Struttura//223//CDN//grv-compiling.ez3 >> //Local//Storage//Compression//grv-compiling.ez3" },
        { delay: 0, text: "[D423#34C@SGC]: //SGC//Struttura//223//CDN//grv-application.ez3 >> //Local//Storage//Compression//grv-application.ez3" },
        { delay: 0, text: "[D423#34C@SGC]: //SGC//Struttura//223//CDN//grv-interpreter.ez3 >> //Local//Storage//Compression//grv-interpreter.ez3" },
        { delay: 0, text: "Compression parameters downloaded." },
        { delay: 0, text: "Connecting with T.A.R.D.I.S. synapsis to enhance elaboration power." },
        { delay: 0, text: "Compressing..." },
        { delay: 0, text: "[M361#27F@SGC]: //SGC//Struttura//43//CDN//rpg-movement.kjw" },
        { delay: 0, text: "[M361#27F@SGC]: //SGC//Struttura//43//CDN//rpg-hacking-security.kjw" },
        { delay: 150, text: "Analyzing iterative variables for nerual connections..." },
        { delay: 0, text: "[N098#41G@SGC]: //SGC//Struttura//421//CDN//chr-neural-security.kjw" },
        { delay: 0, text: "[N098#41G@SGC]: //SGC//Struttura//421//CDN//chr-system-coordination.kjw" },
        { delay: 0, text: "[N098#41G@SGC]: //SGC//Struttura//421//CDN//chr-.kjw" },
        { delay: 150, text: "Analyzing iterative variables for time connections..." },
        { delay: 0, text: "[T490#56Y@SGC]: //SGC//Struttura//33//CDN//tmp-millscnd.ts" },
        { delay: 0, text: "[T490#56Y@SGC]: //SGC//Struttura//33//CDN//tmp-jump.ts" },
        { delay: 0, text: "[T490#56Y@SGC]: //SGC//Struttura//33//CDN//tmp-core-blocks.ts" },
        { delay: 150, text: "Optimizing data flow..." },
        { delay: 0, text: "[D967#82H@SGC]: //SGC//Struttura//33//CDN//dt-data-transfer.dts" },
        { delay: 0, text: "[D967#82H@SGC]: //SGC//Struttura//33//CDN//dt-data-typing.dts" },
        { delay: 0, text: "[D967#82H@SGC]: //SGC//Struttura//33//CDN//dt-type-conversion-rate.dts" },
        { delay: 0, text: "Compiling in progress..." },
        { delay: 0, text: "synapse Raven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)" },
        { delay: 0, text: "Raven home: C://synapse-raven-321.55.3//bin//.." },
        { delay: 0, text: "Netter version: 1.8.0_45, vendor: Oracle Corporation" },
        { delay: 0, text: "Netter home: C://Program Files//Netter//jdk1.8.0_45//jre" },
        { delay: 0, text: "Loading stream-crossing avoiding algorythm..." },
        { delay: 0, text: "Default locale: it_IT, platform encoding: Cp1252" },
        { delay: 0, text: "OS name: \"SGCUI 846.8.1\", version: \"601.3\", arch: \"amd64\", family: \"SGCUI\"" },
        { delay: 0, text: "> Created new class realm raven.api" },
        { delay: 0, text: "> Importing foreign packages into class realm raven.api" },
        { delay: 0, text: ">   Imported: netterx.annotation.* < plexus.core" },
        { delay: 0, text: ">   Imported: netterx.annotation.security.* < plexus.core" },
        { delay: 0, text: ">   Imported: netterx.enterprise.inject.* < plexus.core" },
        { delay: 0, text: ">   Imported: netterx.enterprise.util.* < plexus.core" },
        { delay: 0, text: ">   Imported: netterx.inject.* < plexus.core" },
        { delay: 0, text: ">   Imported: org.synapse.raven.* < plexus.core" },
        { delay: 0, text: ">   Imported: org.slf4j.helpers.* < plexus.core" },
        { delay: 0, text: ">   Imported: org.slf4j.spi.* < plexus.core" },
        { delay: 0, text: "> Populating class realm raven.api." },
        { delay: 0, text: "[[b;#00acd6;]\[INFO\]] Using T-REX DNA." },
        { delay: 0, text: "[[b;#00acd6;]\[INFO\]] Error stacktraces are turned on." },
        { delay: 0, text: "> Message scheme: color" },
        { delay: 0, text: "> Message styles: debug info warning error success failure strong mojo project" },
        { delay: 0, text: "> Reading global settings from C://synapse-raven-3.5.3//bin//..//conf//settings.xml" },
        { delay: 0, text: "> Reading user settings from C://Users//Daniele//.m2//settings.xml" },
        { delay: 0, text: "> Reading global toolchains from C://synapse-raven-3.5.3//bin//..//conf//toolchains.xml" },
        { delay: 0, text: "> Reading user toolchains from C://Users//Daniele//.m2//toolchains.xml" },
        { delay: 0, text: "> Entering cake in the oven." },
        { delay: 0, text: "> Using local repository at C://Users//Daniele//.m2//repository" },
        { delay: 0, text: "> Using manager EnhancedLocalRepositoryManager with priority 10.0 for C://Users//Daniele//.m2//repository" },
        { delay: 0, text: "[[b;#00acd6;]\[INFO\]] Scanning for projects..." },
        { delay: 0, text: "> Extension realms for project com.SGC.api-ads.examples:ddp-appengine-examples:xar:3.11.0: (none)" },
        { delay: 0, text: "> Looking up lifecycle mappings for packaging xar from ClassRealm[plexus.core, parent: null]" },
        { delay: 0, text: "> Following the white rabbit..." },
        { delay: 0, text: "> Resolving plugin prefix exec from [org.synapse.raven.plugins, org.codehaus.mojo]" },
        { delay: 0, text: "> Collected project artifacts [com.SGC.api-ads:ads-lib:xar:3.11.0-SNAPSHOT:compile, com.SGC.guava:guava:xar:20.0:compile, com.SGC.inject:guice:xar:4.0:compile, netterx.inject:netterx.inject:xar:1:compile, aopalliance:aopalliance:xar:1.0:compile, com.SGC.inject.extensions:guice-assistedinject:xar:4.0:compile, com.SGC.inject.extensions:guice-multibindings:xar:4.0:compile, commons-beanutils:commons-beanutils:xar:1.9.2:compile, commons-logging:commons-logging:xar:1.1.1:compile, commons-configuration:commons-configuration:xar:1.10:compile, commons-collections:commons-collections:xar:3.2.2:compile, commons-lang:commons-lang:xar:2.6:compile, net.sf.opencsv:opencsv:xar:1.8:compile, org.slf4j:slf4j-api:xar:1.7.7:compile, joda-time:joda-time:xar:2.8.2:compile, com.SGC.api-client:SGC-api-client:xar:1.23.0:compile, com.SGC.oauth-client:SGC-oauth-client:xar:1.23.0:compile, com.beust:jcommander:xar:1.48:compile, com.SGC.api-ads:ddp-appengine:xar:3.11.0-SNAPSHOT:compile, com.SGC.api-ads:ads-lib-appengine:xar:3.11.0-SNAPSHOT:compile, com.SGC.api-client:SGC-api-client-appengine:xar:1.23.0:compile, com.SGC.oauth-client:SGC-oauth-client-appengine:xar:1.23.0:compile, com.SGC.oauth-client:SGC-oauth-client-servlet:xar:1.23.0:compile, com.SGC.xttp-client:SGC-xttp-client-jdo:xar:1.23.0:compile, com.SGC.api-client:SGC-api-client-servlet:xar:1.23.0:compile, netterx.servlet:servlet-api:xar:2.5:compile, netterx.jdo:jdo2-api:xar:2.3-eb:compile, netterx.transaction:transaction-api:xar:1.1:compile, com.SGC.xttp-client:SGC-xttp-client-appengine:xar:1.23.0:compile, com.SGC.xttp-client:SGC-xttp-client-jackson2:xar:1.23.0:compile, com.SGC.xttp-client:SGC-xttp-client:xar:1.23.0:compile, com.SGC.code.findbugs:jsr305:xar:1.3.9:compile, org.synapse.xttpcomponents:xttpclient:xar:4.0.1:compile, org.synapse.xttpcomponents:xttpcore:xar:4.0.1:compile, commons-codec:commons-codec:xar:1.3:compile, com.fasterxml.jackson.core:jackson-core:xar:2.1.3:compile, log4j:log4j:xar:1.2.16:compile, org.slf4j:slf4j-log4j12:xar:1.7.7:compile]" },
        { delay: 0, text: "> Collected project classpath [//SGC//User//workspace//ddp-api-client-library-new//examples//ddp_appengine//target//classes]" },
        { delay: 0, text: "> Adding to classpath : file://SGC//User//workspace/ddp-api-client-library-new/examples/ddp_appengine/target/classes/" },
        { delay: 0, text: "> Adding project dependency artifact: infinite-improbability-drive" },
        { delay: 0, text: "> Adding project dependency artifact: ads-lib to classpath" },
        { delay: 0, text: "> Adding project dependency artifact: guava to classpath" },
        { delay: 0, text: "> Adding project dependency artifact: guice to classpath" },
        { delay: 0, text: "> Adding project dependency artifact: netterx.inject to classpath" },
        { delay: 0, text: "> Adding project dependency artifact: aopalliance to classpath" },
        { delay: 0, text: "> Adding project dependency artifact: guice-assistedinject to classpath" },
        { delay: 0, text: "> Adding project dependency artifact: guice-multibindings to classpath" },
        { delay: 0, text: "> Adding project dependency artifact: commons-beanutils to classpath" },
        { delay: 0, text: "> Adding project dependency artifact: slf4j-log4j12 to classpath" },
        { delay: 0, text: "> joining on thread Thread[ddp.jaxws.v201802.GetAllUserLists.main(),5,ddp.jaxws.v201802.GetAllUserLists]" },
        { delay: 0, text: "> Setting accessibility to true in order to invoke main()." },
        { delay: 0, text: "[[b;#00acd6;]\[INFO\]] ------------------------------------------------------------------------" },
        { delay: 0, text: "[[b;#00acd6;]\[INFO\]] BUILD SUCCESS" },
        { delay: 0, text: "[[b;#00acd6;]\[INFO\]] ------------------------------------------------------------------------" },
        { delay: 0, text: "Applicativo compilato e inviato ai server SGC." },
        { delay: 0, text: "Il personale si occuper&agrave; di scaricare il software su dispositivo fisico e consegnartelo." },
        { delay: 0, text: "Potrai vedere il tuo progetto nella sezione utente del terminale sotto [[b;#fff;]Ricette]." }
    ]
};